#! /bin/sh

PATH_INFO=$(pwd) export PATH_INFO
SCRIPT_NAME=./perl.pl export SCRIPT_NAME
SCRIPT_FILENAME=./perl.pl export SCRIPT_FILENAME
PATH_TRANSLATED=$PATH_INFO/$SCRIPT_NAME export PATH_TRANSLATED
SERVER_PROTOCOL=http export SERVER_PROTOCOL
REQUEST_METHOD=GET export REQUEST_METHOD
HTTP_HOST=some.server.com export HTTP_HOST
SERVER_PORT=80 export SERVER_PORT
QUERY_STRING="a=b&c=d" export QUERY_STRING

exec ./perl.pl