name: C++ Tests

on:
  push:
    branches: [ "tester" ]
  pull_request:
    branches: [ "tester" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcurl4-openssl-dev

    - name: Build webserver
      run: make
      
    - name: Build tests
      run: |
        cd tests
        make
      
    - name: Start webserver and run tests
      run: |
        nohup ./webserv config/sample.conf > server.log 2>&1 &
        echo $! > webserv.pid

        for i in {1..10}; do
            if curl -4 -s --head http://localhost:8080/ > /dev/null 2>&1; then
                echo "Server is ready"
                break
            fi
            sleep 1
        done

        if ! curl -4 -s --head http://localhost:8080/ > /dev/null 2>&1; then
            echo "Server failed to start in time"
            exit 1
        fi
        
        echo "Server started successfully"
        
        cd tests
        ./test_basic
        TEST_EXIT_CODE=$?
        
        kill $(cat webserv.pid) || true
        
        exit $TEST_EXIT_CODE
