name: C++ Tests

on:
  push:
    branches: [ "tester" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcurl4-openssl-dev net-tools netcat-openbsd

    - name: Build webserver
      run: make
      
    - name: Build tests
      run: |
        cd tests
        make
      
    - name: Start webserver and run tests
      run: |
        ./webserv config/sample.conf > server.log 2>&1 &
        SERVER_PID=$!
        echo $SERVER_PID > webserv.pid
        
        for i in {1..10}; do
          if ps -p $SERVER_PID > /dev/null; then
            echo "Server is running (attempt $i)"
            sleep 1
          else
            echo "Server process died"
            cat server.log
            exit 1
          fi
        done
        
        echo "--- Server Log ---"
        cat server.log
        
        echo "--- Process Info ---"
        ps aux | grep webserv
        
        echo "--- Network Bindings ---"
        sudo netstat -tulpn | grep $SERVER_PID
        
        echo "--- Raw HTTP Response via netcat ---"
        printf "GET / HTTP/1.1\r\nHost: localhost:8080\r\n\r\n" | nc localhost 8080 | hexdump -C
        
        echo "--- Running basic test only ---"
        cd tests
        
        ./test_basic -c "Basic check"
        BASIC_EXIT_CODE=$?
        
        if [ $BASIC_EXIT_CODE -eq 0 ]; then
          echo "Basic test passes, running full test suite"
          ./test_basic
          TEST_EXIT_CODE=$?
        else
          echo "Basic test failed, something is fundamentally wrong"
          TEST_EXIT_CODE=$BASIC_EXIT_CODE
        fi
        
        kill $SERVER_PID || true
        
        exit $TEST_EXIT_CODE