name: C++ Tests

on:
  push:
    branches: [ "tester" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcurl4-openssl-dev net-tools

    - name: Build webserver
      run: make
      
    - name: Build tests
      run: |
        cd tests
        make
      
    - name: Start webserver and run tests
      run: |
        ./webserv config/sample.conf > server.log 2>&1 &
        SERVER_PID=$!
        echo $SERVER_PID > webserv.pid
        
        # Wait briefly for server to initialize
        sleep 5
        
        # Check if process is still running
        if ! ps -p $SERVER_PID > /dev/null; then
          echo "Server process died immediately"
          cat server.log
          exit 1
        fi
        
        echo "--- Server Log ---"
        cat server.log
        
        echo "--- Process Info ---"
        ps aux | grep webserv
        
        echo "--- Network Bindings ---"
        sudo netstat -tulpn | grep $SERVER_PID
        
        echo "--- Connection Tests ---"
        curl -v --head http://127.0.0.1:8080/ || true
        curl -v --head http://localhost:8080/ || true
        curl -v --head http://0.0.0.0:8080/ || true
        
        if curl -s --head --connect-timeout 5 http://127.0.0.1:8080/ > /dev/null 2>&1 || curl -s --head --connect-timeout 5 http://localhost:8080/ > /dev/null 2>&1; then
          echo "Server started successfully"
          cd tests
          ./test_basic
          TEST_EXIT_CODE=$?
        else
          echo "Server failed to respond to requests"
          TEST_EXIT_CODE=1
        fi
        
        kill $SERVER_PID || true
        
        exit $TEST_EXIT_CODE